# Set the version of docker compose to use
version: '3.9'

# The containers that compose the project
services:
  db:
    image: postgres:13
    restart: always
    container_name: club-list-postgres
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tests
    ports:
      - '5432:5432'

  storage: 
    container_name: s3.docker.test
    image: zenko/cloudserver
    ports: 
      - '8000:8000'
    environment:
      - REMOTE_MANAGEMENT_DISABLE=1
      - S3BACKEND=mem
    command: bash -c "yarn start"

  prisma-studio:
    container_name: club-list-prisma-studio
    image: timothyjmiller/prisma-studio:latest
    restart: unless-stopped
    environment:
      - POSTGRES_URL=postgresql://prisma:prisma@db:5432/tests
    env_file:
      - .env.test
    ports:
      - 5555:5555

  web:
    image: node:20.9.0-alpine3.18
    container_name: club-list-web
    environment:
      - OUTER_PORT_FRONTEND=3000
      - INNER_PORT_FRONTEND=5173
      - CODESPACES
    ports:
      - '3000:5173'
    env_file:
      - .env.test
    volumes:
      - ./:/app
      - /app/node_modules/
    working_dir: /app
    command: sh -c "yarn && yarn db:deploy && yarn run seed && yarn dev --host --port 5173"
    depends_on:
      - db
      - storage
