name: publish

on: ['pull_request', 'push']

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          BETA: "true"
      - name: Install dependencies
        run: yarn install
      - name: Check
        run: yarn run check